services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: saul
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db
  mysql:
    image: mysql:latest
    container_name: mysql_bd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data_casa:/var/lib/mysql
      ##- ./mysql_data_clase:/var/lib/mysql
      - ./mysql_shared:/shared-folder
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/my.cnf

volumes:
  mongodb-data:
    driver: local
