services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_bd
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
      - ./shared:/shared-folder
      - ./init.js:/docker-entrypoint-initdb.d/init.js
