services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_bd
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: saul 
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27018:27017"
