services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_bd_1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: saul
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
